services: 
  php-srv: 
    image: imagename
    container_name: php-container 
    ports: 
      - "3000:80"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.php.tls=true"
      - "traefik.http.routers.php.rule=Host(`earthdx.devnerd.store`)"
      - "traefik.http.routers.php.entrypoints=web,websecure"
      - "traefik.http.routers.php.tls.certresolver=letsencrypt"
      # - "traefik.http.services.php.loadbalancer.server.port=3000"
    networks: 
      - proxy
networks: 
  proxy:
    external: true 